name: Dev into master

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the PR- branch
  push:
    branches: [ 'develop' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: npm install
        run: |
          cd simple-blog
          echo -----INSTALLING DEPENDENCIES-----
          npm install
          echo -----INSTALL COMPLETE-----

      - name: npm test
        run: |
          cd simple-blog
          echo -----RUNNING TESTS-----
          npm run test-headless
          echo -----RUNNING TESTS-----

      - name: Merge develop into master
        run: |
          git config user.email "albajo0123@gmail.com"
          git config user.name "InfAurora"
          echo ---------Fetching---------
          git fetch --unshallow
          git pull
          echo ---------Checkout master and Fetch---------
          git checkout master
          git fetch
          echo ---------Merge develop into master and push---------
          git merge --no-ff develop
          git push --force
          echo ---------Checkout develop---------
          git checkout develop
          echo ---------Pull and merge master back into develop---------
          git pull origin master
          git add .
          git commit -m "Merge master into dev"
          git push --force